version: '2'
services:
    mariadb:
        container_name: distributedsystems_mariadb
        image: mariadb:latest
        volumes:
           - ./script/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
           - ds_db_data:/var/lib/mysql
        restart: always
        ports:
           - "3306:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    rabbitmq:
        container_name: distributedsystems_rabbitmq
        image: rabbitmq:3-management
        hostname: my-rabbit
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
volumes:
    ds_db_data:
    rabbitmq_data:
