version: '2'
services:
    mariadb:
        container_name: distributedsystems_mariadb_1
        image: mariadb:latest
        volumes:
           - ds_db_data:/var/lib/mysql
        restart: always
        ports:
           - "3306:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: testdb
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    mariadb:
        container_name: distributedsystems_mariadb_2
        image: mariadb:latest
        volumes:
           - ds_db_data:/var/lib/mysql
        restart: always
        ports:
           - "3307:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: testdb
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    mariadb:
        container_name: distributedsystems_mariadb_3
        image: mariadb:latest
        volumes:
           - ds_db_data:/var/lib/mysql
        restart: always
        ports:
           - "3308:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: testdb
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    mariadb:
        container_name: distributedsystems_mariadb_4
        image: mariadb:latest
        volumes:
           - ds_db_data:/var/lib/mysql
        restart: always
        ports:
           - "3309:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: testdb
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    mariadb:
        container_name: distributedsystems_mariadb_5
        image: mariadb:latest
        volumes:
           - ds_db_data:/var/lib/mysql
        restart: always
        ports:
           - "3310:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: testdb
           MYSQL_USER: root
           MYSQL_PASSWORD: root
    rabbitmq:
        container_name: rabbitmq_queue
        image: rabbitmq:3-management
        volumes:
            - ds_db_data:/var/lib/mysql
volumes:
    ds_db_data:
    
    
    
    mysql -u root -h 127.0.0.1 -P 3306 -proot -e "create database ELENCO; use ELENCO; create TABLE LOG(timestamp TIMESTAMP, idMacchina VARCHAR(255), message VARCHAR(255));"
