version: '2'
services:
    mariadb-1:
        container_name: distributedsystems_mariadb_1
        image: mariadb:latest
        volumes:
           - ds_db_data_1:/var/lib/mysql
        restart: always
        ports:
           - "3306:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: ELENCO
    mariadb-2:
        container_name: distributedsystems_mariadb_2
        image: mariadb:latest
        volumes:
           - ds_db_data_2:/var/lib/mysql
        restart: always
        ports:
           - "3307:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: ELENCO
    mariadb-3:
        container_name: distributedsystems_mariadb_3
        image: mariadb:latest
        volumes:
           - ds_db_data_3:/var/lib/mysql
        restart: always
        ports:
           - "3308:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: ELENCO
    mariadb-4:
        container_name: distributedsystems_mariadb_4
        image: mariadb:latest
        volumes:
           - ds_db_data_4:/var/lib/mysql
        restart: always
        ports:
           - "3309:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: ELENCO
    mariadb-5:
        container_name: distributedsystems_mariadb_5
        image: mariadb:latest
        volumes:
           - ds_db_data_5:/var/lib/mysql
        restart: always
        ports:
           - "3310:3306"
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: ELENCO
    rabbitmq:
        container_name: distributedsystems_rabbitmq
        image: rabbitmq:3-management
        hostname: my-rabbit
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
volumes:
    ds_db_data_1:
    ds_db_data_2:
    ds_db_data_3:
    ds_db_data_4:
    ds_db_data_5:
    rabbitmq_data:

